apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework.fullname" . }}
  labels:
    app: {{ include "homework.fullname" . }}
  {{- include "homework.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.homework.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "homework.fullname" . }}
  {{- include "homework.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        app: {{ include "homework.fullname" . }}
    {{- include "homework.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.homework.name }}
          image: "{{ .Values.homework.image.repository }}:{{.Chart.AppVersion }}"
          ports:
            - name: {{.Values.homework.service.name}}
              containerPort: {{.Values.homework.service.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{.Values.homework.service.name}}
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{.Values.homework.service.name}}
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homework-secret
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: homework-config
            - name: DATABASE_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_DATABASE
                  name: homework-config
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_USERNAME
                  name: homework-config