{{- if .Values.homework.ingress.enabled -}}
        {{- $fullName := include "homework.fullname" . -}}
  {{- $svcPort := .Values.homework.service.port -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "homework.fullname" . }}
    {{- include "homework.labels" . | nindent 4 }}
  {{- with .Values.homework.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.homework.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
                {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
        {{- end }}
  {{- end }}
