apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework.fullname" . }}-authserver
  labels:
          {{- include "homework.labels" . | nindent 4 }}-authserver
spec:
  type: {{ .Values.authserver.service.type }}
  ports:
    - port: {{ .Values.authserver.service.port }}
      targetPort: {{.Values.authserver.service.portName}}
      protocol: TCP
      name: {{.Values.authserver.service.portName}}
  selector:
          {{- include "homework.selectorLabels" . | nindent 4 }}-authserver
