apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
data:
  DATABASE_HOST: {{ include "billingdb.fullname" . }}
  DATABASE_DATABASE: {{.Values.billingdb.postgresqlDatabase}}
  DATABASE_USERNAME: {{.Values.billingdb.postgresqlUsername}}
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-secret
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.billingdb.postgresqlPassword | b64enc }}