# Default values for package.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: aliensoul/homework

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  annotations: {nginx.ingress.kubernetes.io/rewrite-target: /$2}
  hosts:
    - host: arch.homework
      paths:
        path: /otusapp/k.verzunov($|/)(.*)



postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: homework

  service:
    type: NodePort
    port: 5432

  persistence:
    size: 1Gi


