# Default values for package.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

authserver:
  replicaCount: 1
  name: authserver
  image:
    repository: aliensoul/auth-server

  service:
    type: NodePort
    port: 8080
    portName: authserver-http

  ingress:
    enabled: true
    hosts:
      - host: arch.homework


homework:
  name: homework
  replicaCount: 2

  image:
    repository: aliensoul/homework
  service:
    type: NodePort
    port: 8000
    name: homework-http

  ingress:
    enabled: true
    annotations: {nginx.ingress.kubernetes.io/rewrite-target: /$2,
                  nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id",
                  nginx.ingress.kubernetes.io/auth-signin: "http://$host/signin",
                  nginx.ingress.kubernetes.io/auth-url: "http://homework-authserver.homework.svc.cluster.local:8080/auth"}
    hosts:
      - host: arch.homework
        paths:
          path: /otusapp/k.verzunov($|/)(.*)



postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: homework

  service:
    type: NodePort
    port: 5432

  persistence:
    size: 1Gi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true


prometheus-operator:
  enabled: false

  serviceMonitor:
    enabled: false

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}

nginx:
  enabled: false

  controller:
    kind: DaemonSet

    reportNodeInternalIp: true

    daemonset:
      useHostPort: true
      hostPorts:
        http: 80
        https: 443

    service:
      type: NodePort

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true