apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
data:
  DATABASE_HOST: {{ include "postgresql.fullname" . }}
  DATABASE_DATABASE: {{.Values.postgresql.postgresqlDatabase}}
  DATABASE_USERNAME: {{.Values.postgresql.postgresqlUsername}}
---
apiVersion: v1
kind: Secret
metadata:
  name: homework-secret
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}