apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework.fullname" . }}
  labels:
  {{- include "homework.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "homework.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "homework.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{.Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homework-secret
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: homework-config
            - name: DATABASE_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_DATABASE
                  name: homework-config
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_USERNAME
                  name: homework-config