cp-zookeeper:
  enabled: true
  servers: 3
  image: confluentinc/cp-zookeeper
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    dataDirSize: 1Gi
    dataLogDirSize: 1Gi
  resources: {}

cp-kafka:
  enabled: true
  brokers: 3
  image: confluentinc/cp-enterprise-kafka
  imageTag: 5.2.1
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    # storageClass: ""
    size: 1Gi
    disksPerBroker: 1
  nodeport:
    enabled: true
    servicePort: 19092
    firstListenerPort: 31090
  configurationOverrides:
    "offsets.topic.replication.factor": "3"
    # "default.replication.factor": 3
    # "min.insync.replicas": 2
    # "auto.create.topics.enable": false

    ## Options required for external access via NodePort
    ## ref:
    ## - http://kafka.apache.org/documentation/#security_configbroker
    ## - https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic
    ##
    ## Advertised listeners will use the firstListenerPort value as it's default unless overridden here.
    ## Setting "advertised.listeners" here appends to "PLAINTEXT://${POD_IP}:9092,"
    "advertised.listeners": |-
      EXTERNAL://localhost:$((31090 + ${KAFKA_BROKER_ID}))
    "listener.security.protocol.map": |-
      PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

cp-schema-registry:
  enabled: false

cp-kafka-rest:
  enabled: false

cp-kafka-connect:
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: false